"""add reactions field to message model

Revision ID: 827a801e11dc
Revises: f0f3503a9851
Create Date: 2025-12-11 10:34:46.248747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '827a801e11dc'
down_revision: Union[str, None] = 'f0f3503a9851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reactions')
    # ### end Alembic commands ###
