"""describe change

Revision ID: eb6a66bd3f23
Revises: 
Create Date: 2025-11-27 15:15:46.232041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb6a66bd3f23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create users first (messages and message_deletions depend on users)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_sub', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # create conversations without last_message columns first to avoid circular FK
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # create messages (depends on conversations and users)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('delivered_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seen_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_for_everyone', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)

    # create message_deletions (depends on messages and users)
    op.create_table('message_deletions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deletions_message_id'), 'message_deletions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_deletions_user_id'), 'message_deletions', ['user_id'], unique=False)
    op.create_index('uq_message_deletions_pair', 'message_deletions', ['message_id', 'user_id'], unique=True)

    # now add last_message columns to conversations and FK to messages
    op.add_column('conversations', sa.Column('last_message_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('last_message_preview', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('last_message_created_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_conversations_last_message_id'), 'conversations', ['last_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_message_deletions_pair', table_name='message_deletions')
    op.drop_index(op.f('ix_message_deletions_user_id'), table_name='message_deletions')
    op.drop_index(op.f('ix_message_deletions_message_id'), table_name='message_deletions')
    op.drop_table('message_deletions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_conversation_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_last_message_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
